// View Visitors
GET http://localhost:4000/viewvisitor
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTk3ZmJhZDg5M2IyMzk2OGU1MDhiNTIiLCJpYXQiOjE3MDQ0NjA3MDYsImV4cCI6MTcwNDQ2NDMwNn0.wuYUHTIUNRgit5Z1FrqBZbHdeoF2HPcv5fDQSgjTfZM

###
// Register Admin
POST http://localhost:4000/registeradmin
Content-Type: application/json

{
    "username": "yuki",
    "password": 9000
}

###
// Admin Login
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "yuki",
    "password": 9000
}

###
// Register a Visitor
POST http://localhost:4000/registervisitor
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTk3ZmJhZDg5M2IyMzk2OGU1MDhiNTIiLCJpYXQiOjE3MDQ0NTkyMDUsImV4cCI6MTcwNDQ2MjgwNX0.6A_ZdBRMtRKKSTx2I5bnOPi3oflVD5xfJjFouvDFA1w

{
    "Name": "itto",
    "Age": "23",
    "Gender": "male",
    "Address": "inazuma",
    "Zipcode": "9898",
    "Relation": "onikabuto fight"
}


###
//Admin issue visitor pass
POST http://localhost:4000/issuevisitorpass
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTk3ZmJhZDg5M2IyMzk2OGU1MDhiNTIiLCJpYXQiOjE3MDQ0NjA3NTEsImV4cCI6MTcwNDQ2NDM1MX0.IDIQDVen_tBQCUSqUUw0Kc2t8-vmJ7SRerGKCa3O8FY

{
    "visitorId": "6597fc03893b23968e508b53",
    "issuedBy": "yuki",
    "validUntil": "2023-12-31T23:59:59"
}




###
//Visitor to Retrieve Their Pass          //visitor ID
GET http://localhost:4000/retrievepass/6597fc03893b23968e508b53



###
// Update Visitor                           //visitor ID
PATCH http://localhost:4000/updatevisitor/65885309e00fafde3f572263
Content-Type: application/json         
Authorization: Bearer 

{
    "Name": "juliana",
    "Age": "50",
    "Gender": "female",
    "Address": "bukit bintang",
    "Zipcode": "47300",
    "Relation": "honeymoon"
}


###
// Delete Visitor                           //visitor ID
DELETE http://localhost:4000/deletevisitor/6587b6a9df5531ab2ec05054
Authorization: Bearer 
