// View Visitors
GET http://localhost:4000/viewvisitor
Authorization: Bearer 

###
// Register Admin
POST http://localhost:4000/registeradmin
Content-Type: application/json

{
    "username": "syahirah",
    "password": 8877
}

###
// Admin Login
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "syahirah",
    "password": 8877
}

###
// Register a Visitor
POST http://localhost:4000/registervisitor
Content-Type: application/json
Authorization: Bearer 
{
    "Name": "keima",
    "Age": "24",
    "Gender": "female",
    "Address": "konoha",
    "Zipcode": "34000",
    "Relation": "balik umah"
}


###
//Admin issue visitor pass
POST http://localhost:4000/issuevisitorpass
Content-Type: application/json
Authorization: Bearer 

{
    "visitorId": "658aa47fb8cd40c4b34204b4",
    "issuedBy": "syahirah",
    "validUntil": "2023-12-31T23:59:59"
}




###
//Visitor to Retrieve Their Pass          //visitor ID
GET http://localhost:4000/retrievepass/658aa47fb8cd40c4b34204b4



###
// Update Visitor                           //visitor ID
PATCH http://localhost:4000/updatevisitor/65885309e00fafde3f572263
Content-Type: application/json         
Authorization: Bearer 

{
    "Name": "juliana",
    "Age": "50",
    "Gender": "female",
    "Address": "bukit bintang",
    "Zipcode": "47300",
    "Relation": "honeymoon"
}


###
// Delete Visitor                           //visitor ID
DELETE http://localhost:4000/deletevisitor/6587b6a9df5531ab2ec05054
Authorization: Bearer 
